# https://taskfile.dev
version: '3'

tasks:
  build-guest:
    cmds:
      - tinygo build -target ../wasm-target.json ./guest
      - wasm-strip guest.wasm
      - ls -lh guest.wasm

  run:
    cmds:
      - task: build-guest
      - go run .
